codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 70%         # cobertura mínima deseada
        threshold: 5%       # tolerancia de caída
    patch:
      default:
        target: 60%

ignore:
  - "tests/"
  - "**/__init__.py"

comment:
  layout: "diff"
  behavior: default
