services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: doubleit-backend
    ports:
      - "8000:8080"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: doubleit-frontend
    ports:
      - "8501:8080"
    restart: unless-stopped
    depends_on:
      - backend
