[lint]
# Selección de reglas por origen (plugins)
select = [
    "B",     # flake8-bugbear: errores comunes y buenas prácticas
    "C90",   # mccabe: complejidad ciclomática
    "E",     # pycodestyle: estilo PEP8
    "F",     # pyflakes: errores simples
    "W",     # warnings: advertencias generales
    "PL",    # pylint: errores estáticos y convención
    "I",     # isort: orden de imports
    "S",     # flake8-bandit: seguridad
    "UP",    # pyupgrade: código moderno
    "RUF",   # reglas propias de Ruff
    "SIM",   # flake8-simplify: simplificaciones recomendadas
    "TRY",   # tryceratops: manejo de errores
]

# Reglas ignoradas puntualmente
ignore = [
    "E203",      # Conflicto con black (espaciado en slicing)
    "E501",      # Longitud de línea, delegada al formatter
    "S101",      # Uso de assert, permitido en tests
    "PLR0913",   # Muchos argumentos en funciones (aceptado en ML)
]

# Correcciones automáticas habilitadas
fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true

[lint.mccabe]
max-complexity = 10

[lint.isort]
