name: CI/CD

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint-and-format:
    name: Pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run pre-commit checks
        run: uvx pre-commit run --all-files --show-diff-on-failure --color=always

  test:
    name: Run tests and coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install project dependencies
        run: uv sync --group back

      - name: Run tests with coverage
        run: uv run pytest --cov --cov-branch --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
